/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcercaDeRouteImport } from './routes/acerca-de'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as PropiedadesRouteImport } from './routes/propiedades'
import { Route as TasacionesRouteImport } from './routes/tasaciones'
import { Route as PropiedadIdRouteImport } from './routes/propiedad.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcercaDeRoute = AcercaDeRouteImport.update({
  id: '/acerca-de',
  path: '/acerca-de',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesRoute = PropiedadesRouteImport.update({
  id: '/propiedades',
  path: '/propiedades',
  getParentRoute: () => rootRouteImport,
} as any)
const TasacionesRoute = TasacionesRouteImport.update({
  id: '/tasaciones',
  path: '/tasaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadIdRoute = PropiedadIdRouteImport.update({
  id: '/propiedad/$id',
  path: '/propiedad/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acerca-de': typeof AcercaDeRoute
  '/admin': typeof AdminRoute
  '/contacto': typeof ContactoRoute
  '/propiedades': typeof PropiedadesRoute
  '/tasaciones': typeof TasacionesRoute
  '/propiedad/$id': typeof PropiedadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acerca-de': typeof AcercaDeRoute
  '/admin': typeof AdminRoute
  '/contacto': typeof ContactoRoute
  '/propiedades': typeof PropiedadesRoute
  '/tasaciones': typeof TasacionesRoute
  '/propiedad/$id': typeof PropiedadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acerca-de': typeof AcercaDeRoute
  '/admin': typeof AdminRoute
  '/contacto': typeof ContactoRoute
  '/propiedades': typeof PropiedadesRoute
  '/tasaciones': typeof TasacionesRoute
  '/propiedad/$id': typeof PropiedadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acerca-de'
    | '/admin'
    | '/contacto'
    | '/propiedades'
    | '/tasaciones'
    | '/propiedad/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acerca-de'
    | '/admin'
    | '/contacto'
    | '/propiedades'
    | '/tasaciones'
    | '/propiedad/$id'
  id:
    | '__root__'
    | '/'
    | '/acerca-de'
    | '/admin'
    | '/contacto'
    | '/propiedades'
    | '/tasaciones'
    | '/propiedad/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcercaDeRoute: typeof AcercaDeRoute
  AdminRoute: typeof AdminRoute
  ContactoRoute: typeof ContactoRoute
  PropiedadesRoute: typeof PropiedadesRoute
  TasacionesRoute: typeof TasacionesRoute
  PropiedadIdRoute: typeof PropiedadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acerca-de': {
      id: '/acerca-de'
      path: '/acerca-de'
      fullPath: '/acerca-de'
      preLoaderRoute: typeof AcercaDeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades': {
      id: '/propiedades'
      path: '/propiedades'
      fullPath: '/propiedades'
      preLoaderRoute: typeof PropiedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasaciones': {
      id: '/tasaciones'
      path: '/tasaciones'
      fullPath: '/tasaciones'
      preLoaderRoute: typeof TasacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedad/$id': {
      id: '/propiedad/$id'
      path: '/propiedad/$id'
      fullPath: '/propiedad/$id'
      preLoaderRoute: typeof PropiedadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcercaDeRoute: AcercaDeRoute,
  AdminRoute: AdminRoute,
  ContactoRoute: ContactoRoute,
  PropiedadesRoute: PropiedadesRoute,
  TasacionesRoute: TasacionesRoute,
  PropiedadIdRoute: PropiedadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
